version: '3.1'
services:
  app:
    build: ./
    ports:
      - 3000:3000
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
    entrypoint: ["/app/lib/docker-entrypoint.sh"]
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: hunter2
      POSTGRES_USER: megaphone